### ISSUE TITLE
error alta pago

### ISSUE THREAD

**Issue by Marie084** [jlopezjuy/NicolJeniffer#1]
En lugar de llamarse "alta pago" podría llamarse Nuevo pago.
El input text denominado alta pago, en sus items: importe y numero de recibo, acepta letras y no se actualiza al cerrar el input.

**Comment by jlopezjuy** [comment]
Campos cambiados, y funcionalidad de recibo de pagos funciona correctamente, ya no queda texto al cerrar el dialog.

**Comment by Marie084** [comment]
👍😀
